// =====================================================================
// NORIKAE MASTER - 東京メトロ乗り換え4択クイズ データ
// デザイン: 路線カラー重視・子ども向けモバイル
// =====================================================================

export interface QuizQuestion {
  id: number;
  question: string;
  hint?: string;
  choices: string[];
  correctIndex: number;
  explanation: string;
  lineColor: string;       // 問題に関連する路線カラー
  lineColor2?: string;     // 2路線絡む場合の第2カラー
  lineName: string;        // 路線名（バッジ表示用）
  lineName2?: string;
  difficulty: 'easy' | 'normal' | 'hard';
  emoji: string;           // 問題イメージ絵文字
}

export const LINE_COLORS: Record<string, string> = {
  '銀座線':   '#F5A623',
  '丸ノ内線': '#E60012',
  '日比谷線': '#9B9EA0',
  '東西線':   '#009BBF',
  '千代田線': '#00BB85',
  '有楽町線': '#C1A900',
  '半蔵門線': '#8F76D6',
  '南北線':   '#00AC9B',
  '副都心線': '#9C5E31',
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ===== EASY =====
  {
    id: 1,
    question: '銀座線と丸ノ内線が\nおなじホームで\nのりかえできる駅は？',
    hint: 'アカサカ…',
    choices: ['表参道', '赤坂見附', '溜池山王', '銀座'],
    correctIndex: 1,
    explanation: '赤坂見附駅は島式ホームの両側に銀座線と丸ノ内線が来るよ！ホームをわたるだけでのりかえできる、すごく便利な駅だよ。',
    lineColor: LINE_COLORS['銀座線'],
    lineColor2: LINE_COLORS['丸ノ内線'],
    lineName: '銀座線',
    lineName2: '丸ノ内線',
    difficulty: 'easy',
    emoji: '🚇',
  },
  {
    id: 2,
    question: '半蔵門線に乗ったまま\n東急田園都市線に\nいける駅は？',
    hint: 'スクランブル交差点が有名！',
    choices: ['渋谷', '表参道', '押上', '三軒茶屋'],
    correctIndex: 0,
    explanation: '渋谷駅では半蔵門線と東急田園都市線がおなじホームでつながっているよ。のりかえなしで中央林間まで行けるよ！',
    lineColor: LINE_COLORS['半蔵門線'],
    lineColor2: '#E9171F',
    lineName: '半蔵門線',
    lineName2: '田園都市線',
    difficulty: 'easy',
    emoji: '🌀',
  },
  {
    id: 3,
    question: '東西線に乗ったまま\nJR中央・総武線に\nいける駅は？',
    hint: '東京の西のほうにある駅だよ',
    choices: ['大手町', '西船橋', '中野', '茅場町'],
    correctIndex: 2,
    explanation: '中野駅では東西線とJR中央・総武線がつながっているよ。三鷹まで直通で行けるよ！',
    lineColor: LINE_COLORS['東西線'],
    lineColor2: '#F15A22',
    lineName: '東西線',
    lineName2: 'JR中央・総武線',
    difficulty: 'easy',
    emoji: '🚂',
  },
  {
    id: 4,
    question: '南北線に乗ったまま\n東急目黒線に\nいける駅は？',
    hint: 'め…ぐ…',
    choices: ['目黒', '白金台', '溜池山王', '後楽園'],
    correctIndex: 0,
    explanation: '目黒駅では南北線と東急目黒線がおなじホームでつながっているよ。都営三田線も直通で走っているよ！',
    lineColor: LINE_COLORS['南北線'],
    lineColor2: '#00BB85',
    lineName: '南北線',
    lineName2: '東急目黒線',
    difficulty: 'easy',
    emoji: '🌿',
  },
  {
    id: 5,
    question: '副都心線に乗ったまま\n東急東横線に\nいける駅は？',
    hint: 'ハチ公がいる駅！',
    choices: ['池袋', '新宿三丁目', '渋谷', '和光市'],
    correctIndex: 2,
    explanation: '渋谷駅では副都心線と東急東横線がおなじホームでつながっているよ。元町・中華街まで直通で行けるよ！',
    lineColor: LINE_COLORS['副都心線'],
    lineColor2: '#E9171F',
    lineName: '副都心線',
    lineName2: '東急東横線',
    difficulty: 'easy',
    emoji: '🐕',
  },
  {
    id: 6,
    question: '千代田線に乗ったまま\n小田急線に\nいける駅は？',
    hint: 'よよぎ…',
    choices: ['表参道', '代々木上原', '北千住', '綾瀬'],
    correctIndex: 1,
    explanation: '代々木上原駅では千代田線と小田急線がつながっているよ。本厚木や唐木田まで直通で行けるよ！',
    lineColor: LINE_COLORS['千代田線'],
    lineColor2: '#0066B3',
    lineName: '千代田線',
    lineName2: '小田急線',
    difficulty: 'easy',
    emoji: '🏔️',
  },

  // ===== NORMAL =====
  {
    id: 7,
    question: '東京メトロで\n改札を出ないで乗り換えると\n何分以内にしないといけない？',
    hint: '1時間は何分？',
    choices: ['30分', '45分', '60分', '90分'],
    correctIndex: 2,
    explanation: '東京メトロでは改札を出て別の路線に乗り換えるとき、60分（1時間）以内なら追加料金なしで乗れるよ！これを「60分ルール」というよ。',
    lineColor: '#003087',
    lineName: '東京メトロ',
    difficulty: 'normal',
    emoji: '⏰',
  },
  {
    id: 8,
    question: '有楽町線と副都心線が\n東武東上線に\nつながっている駅は？',
    hint: '埼玉県にある駅だよ',
    choices: ['池袋', '小竹向原', '和光市', '志木'],
    correctIndex: 2,
    explanation: '和光市駅では有楽町線・副都心線と東武東上線がつながっているよ。森林公園や小川町まで直通で行けるよ！',
    lineColor: LINE_COLORS['有楽町線'],
    lineColor2: LINE_COLORS['副都心線'],
    lineName: '有楽町線',
    lineName2: '副都心線',
    difficulty: 'normal',
    emoji: '🌲',
  },
  {
    id: 9,
    question: '半蔵門線に乗ったまま\n東武スカイツリーラインに\nいける駅は？',
    hint: 'スカイツリーの近くにある駅！',
    choices: ['北千住', '押上', '渋谷', '錦糸町'],
    correctIndex: 1,
    explanation: '押上駅では半蔵門線と東武スカイツリーラインがつながっているよ。日光や鬼怒川まで直通で行けるよ！',
    lineColor: LINE_COLORS['半蔵門線'],
    lineColor2: '#F5A623',
    lineName: '半蔵門線',
    lineName2: '東武スカイツリーライン',
    difficulty: 'normal',
    emoji: '🗼',
  },
  {
    id: 10,
    question: '東西線が東葉高速線に\nつながっている駅は？',
    hint: '千葉県にある駅だよ',
    choices: ['中野', '大手町', '西船橋', '葛西'],
    correctIndex: 2,
    explanation: '西船橋駅では東西線と東葉高速線がつながっているよ。東葉勝田台まで直通で行けるよ！',
    lineColor: LINE_COLORS['東西線'],
    lineColor2: '#E60012',
    lineName: '東西線',
    lineName2: '東葉高速線',
    difficulty: 'normal',
    emoji: '🌊',
  },
  {
    id: 11,
    question: '九段下駅でおなじホームで\nのりかえできる2つの路線は？',
    hint: '2013年にかべが取り除かれたよ',
    choices: [
      '銀座線と丸ノ内線',
      '東西線と半蔵門線',
      '千代田線と南北線',
      '日比谷線と有楽町線',
    ],
    correctIndex: 1,
    explanation: '九段下駅では2013年にホームのかべが取り除かれて、東西線と半蔵門線がおなじホームでのりかえできるようになったよ！都営新宿線は別の改札だよ。',
    lineColor: LINE_COLORS['東西線'],
    lineColor2: LINE_COLORS['半蔵門線'],
    lineName: '東西線',
    lineName2: '半蔵門線',
    difficulty: 'normal',
    emoji: '🏯',
  },
  {
    id: 12,
    question: '大手町駅には東京メトロの\n何路線が乗り入れている？',
    hint: '4つの線が集まる大きな駅！',
    choices: ['2路線', '3路線', '4路線', '5路線'],
    correctIndex: 2,
    explanation: '大手町駅には丸ノ内線・東西線・千代田線・半蔵門線の4路線が乗り入れているよ。都営三田線も近くにあるよ！',
    lineColor: LINE_COLORS['丸ノ内線'],
    lineColor2: LINE_COLORS['東西線'],
    lineName: '大手町',
    difficulty: 'normal',
    emoji: '🏢',
  },

  // ===== HARD =====
  {
    id: 13,
    question: '東京メトロで一番\n乗り換えに歩く距離が長い\nのはどれ？',
    hint: '765メートルも歩くよ！',
    choices: [
      '渋谷駅（銀座線↔副都心線）',
      '大手町駅（丸ノ内線↔半蔵門線）',
      '国会議事堂前（丸ノ内線）↔溜池山王（銀座線）',
      '池袋駅（丸ノ内線↔有楽町線）',
    ],
    correctIndex: 2,
    explanation: '国会議事堂前駅（丸ノ内線）から溜池山王駅（銀座線）への乗り換えは765メートルもあるよ！東京駅の八重洲口から八丁堀まで歩く距離と同じくらいだよ。',
    lineColor: LINE_COLORS['丸ノ内線'],
    lineColor2: LINE_COLORS['銀座線'],
    lineName: '丸ノ内線',
    lineName2: '銀座線',
    difficulty: 'hard',
    emoji: '👟',
  },
  {
    id: 14,
    question: '南北線が埼玉高速鉄道に\nつながっている駅は？',
    hint: 'あかばね…いわ…',
    choices: ['浦和美園', '赤羽岩淵', '王子', '志茂'],
    correctIndex: 1,
    explanation: '赤羽岩淵駅では南北線と埼玉高速鉄道がつながっているよ。浦和美園まで直通で行けるよ！',
    lineColor: LINE_COLORS['南北線'],
    lineColor2: '#E60012',
    lineName: '南北線',
    lineName2: '埼玉高速鉄道',
    difficulty: 'hard',
    emoji: '⚽',
  },
  {
    id: 15,
    question: '千代田線がJR常磐線に\nつながっている駅は？',
    hint: 'あや…せ',
    choices: ['北千住', '綾瀬', '松戸', '我孫子'],
    correctIndex: 1,
    explanation: '綾瀬駅では千代田線とJR常磐線各停がつながっているよ。取手や我孫子まで直通で行けるよ！',
    lineColor: LINE_COLORS['千代田線'],
    lineColor2: '#F15A22',
    lineName: '千代田線',
    lineName2: 'JR常磐線',
    difficulty: 'hard',
    emoji: '🌾',
  },
  {
    id: 16,
    question: '有楽町線・副都心線が\n西武池袋線につながっている\n駅は？',
    hint: 'こたけ…むかいはら',
    choices: ['池袋', '練馬', '小竹向原', '石神井公園'],
    correctIndex: 2,
    explanation: '小竹向原駅では有楽町線・副都心線と西武池袋線がつながっているよ。飯能や所沢まで直通で行けるよ！',
    lineColor: LINE_COLORS['副都心線'],
    lineColor2: '#0066B3',
    lineName: '副都心線',
    lineName2: '西武池袋線',
    difficulty: 'hard',
    emoji: '🎪',
  },
  {
    id: 17,
    question: '副都心線の特急「Fライナー」は\nどこからどこまで走っている？',
    hint: '神奈川県の港町まで行くよ！',
    choices: [
      '和光市〜渋谷',
      '飯能〜元町・中華街',
      '池袋〜横浜',
      '小竹向原〜みなとみらい',
    ],
    correctIndex: 1,
    explanation: 'Fライナーは西武線の飯能から東武線・副都心線・東急東横線・みなとみらい線を通って元町・中華街まで走る特急列車だよ！',
    lineColor: LINE_COLORS['副都心線'],
    lineColor2: '#E9171F',
    lineName: '副都心線',
    lineName2: 'Fライナー',
    difficulty: 'hard',
    emoji: '⚡',
  },
  {
    id: 18,
    question: '日比谷線と東武スカイツリーラインが\nつながっている駅は？',
    hint: 'きた…せん…じゅ',
    choices: ['押上', '北千住', '曳舟', '東武動物公園'],
    correctIndex: 1,
    explanation: '北千住駅では日比谷線と東武スカイツリーラインがつながっているよ。千代田線・JR常磐線も乗り入れる大きな駅だよ！',
    lineColor: LINE_COLORS['日比谷線'],
    lineColor2: '#F5A623',
    lineName: '日比谷線',
    lineName2: '東武スカイツリーライン',
    difficulty: 'hard',
    emoji: '🦁',
  },
];

export const DIFFICULTY_LABELS = {
  easy:   { label: 'かんたん', color: '#4CAF50', emoji: '⭐' },
  normal: { label: 'ふつう',   color: '#FF9800', emoji: '⭐⭐' },
  hard:   { label: 'むずかしい', color: '#F44336', emoji: '⭐⭐⭐' },
};
