/*
 * Voiceprint Authentication Firmware for CH32V003
 * 
 * Features:
 * - ADC sampling from analog mic (PA1)
 * - MFCC feature extraction (fixed-point Q15)
 * - Template matching with cosine similarity
 * - Servo control for lock (PD4)
 * - Serial output to UiPath (PA2/PA3)
 *
 * Hardware:
 * - MIC: MAX4466 → PA1 (ADC1_CH1)
 * - Servo: PD4 (Timer2 CH1)
 * - UART: PA2(TX), PA3(RX) @ 115200
 */

#include "ch32v003fun.h"
#include <stdio.h>
#include <string.h>

// ============= Configuration =============
#define ADC_SAMPLE_RATE     8000        // 8kHz sampling
#define FRAME_SIZE          160         // 20ms @ 8kHz = 160 samples
#define NUM_MFCC            13          // MFCC coefficients
#define NUM_SPEAKERS        3           // Number of registered users
#define AUTH_THRESHOLD      0.85f       // Cosine similarity threshold

// ============= Voice Templates =============
// Generated by python_training/generate_template.py --mode export
// Include the generated header here
#include "speaker_templates.h"

// ============= Global Buffers =============
// Ring buffer for ADC samples (2KB RAM constraint)
int16_t adc_buffer[FRAME_SIZE];
volatile uint16_t adc_index = 0;
volatile uint8_t frame_ready = 0;

// MFCC features (current frame)
float mfcc_features[NUM_MFCC];

// ============= Function Prototypes =============
void SystemInit(void);
void ADC_Init(void);
void Timer_Init(void);
void UART_Init(void);
void Servo_Init(void);

void Process_Frame(void);
void Extract_MFCC(int16_t* samples, float* mfcc);
float Cosine_Similarity(float* a, float* b, int dim);
int Authenticate(float* features);

void Unlock_Servo(void);
void Send_Result(int speaker_id);

// ============= Main =============
int main(void)
{
    SystemInit();
    
    // Initialize peripherals
    UART_Init();      // For UiPath communication
    ADC_Init();       // For microphone input
    Timer_Init();     // For ADC sampling trigger
    Servo_Init();     // For lock control
    
    printf("Voiceprint Auth Ready\n");
    
    while(1)
    {
        if(frame_ready)
        {
            frame_ready = 0;
            
            // Process current frame
            Process_Frame();
            
            // Authenticate
            int speaker_id = Authenticate(mfcc_features);
            
            if(speaker_id >= 0)
            {
                printf("AUTH: %d\n", speaker_id);
                Send_Result(speaker_id);
                Unlock_Servo();
            }
        }
    }
}

// ============= ADC Interrupt Handler =============
// Called at 8kHz by Timer2 trigger
void ADC1_COMP_IRQHandler(void) __attribute__((interrupt));
void ADC1_COMP_IRQHandler(void)
{
    if(ADC1->STATR & ADC_STATR_EOC)
    {
        adc_buffer[adc_index++] = (int16_t)(ADC1->RDATAR & 0x3FF);  // 10-bit ADC
        
        if(adc_index >= FRAME_SIZE)
        {
            adc_index = 0;
            frame_ready = 1;
        }
        
        ADC1->STATR = ~ADC_STATR_EOC;  // Clear EOC flag
    }
}

// ============= Processing Functions =============
void Process_Frame(void)
{
    Extract_MFCC(adc_buffer, mfcc_features);
}

// Simplified MFCC extraction (placeholder - full implementation needed)
void Extract_MFCC(int16_t* samples, float* mfcc)
{
    // TODO: Implement fixed-point MFCC
    // 1. Pre-emphasis filter
    // 2. Hamming window
    // 3. FFT (use lookup tables for sin/cos)
    // 4. Mel filterbank
    // 5. DCT
    
    // For now, simple energy features as placeholder
    float energy = 0;
    for(int i = 0; i < FRAME_SIZE; i++)
    {
        energy += samples[i] * samples[i];
    }
    mfcc[0] = energy / FRAME_SIZE;
    
    // Zero-crossing rate
    int zcr = 0;
    for(int i = 1; i < FRAME_SIZE; i++)
    {
        if((samples[i] >= 0 && samples[i-1] < 0) || 
           (samples[i] < 0 && samples[i-1] >= 0))
        {
            zcr++;
        }
    }
    mfcc[1] = (float)zcr / FRAME_SIZE;
    
    // Remaining MFCCs would be computed from FFT...
    for(int i = 2; i < NUM_MFCC; i++)
    {
        mfcc[i] = 0.0f;
    }
}

float Cosine_Similarity(float* a, float* b, int dim)
{
    float dot = 0, norm_a = 0, norm_b = 0;
    
    for(int i = 0; i < dim; i++)
    {
        dot += a[i] * b[i];
        norm_a += a[i] * a[i];
        norm_b += b[i] * b[i];
    }
    
    if(norm_a == 0 || norm_b == 0) return 0;
    
    return dot / (sqrtf(norm_a) * sqrtf(norm_b));
}

int Authenticate(float* features)
{
    int best_id = -1;
    float best_sim = 0;
    
    for(int i = 0; i < NUM_SPEAKERS; i++)
    {
        float sim = Cosine_Similarity(features, 
                                       (float*)speaker_templates[i], 
                                       NUM_MFCC);
        
        if(sim > best_sim && sim >= AUTH_THRESHOLD)
        {
            best_sim = sim;
            best_id = i;
        }
    }
    
    return best_id;
}

// ============= Output Functions =============
void Unlock_Servo(void)
{
    // Rotate servo to 90 degrees (unlock)
    // PWM duty cycle for 90° ≈ 7.5% @ 50Hz
    Timer2->CH1CVR = 6000;  // Adjust based on your servo
    
    Delay_Ms(3000);  // Hold for 3 seconds
    
    // Return to 0 degrees (lock)
    Timer2->CH1CVR = 3000;
}

void Send_Result(int speaker_id)
{
    // Send to UiPath via UART
    printf("UNLOCK_OK,ID=%d\n", speaker_id);
}

// ============= Peripheral Initialization =============
void UART_Init(void)
{
    // PA2 = TX, PA3 = RX
    GPIOA->CFGLR &= ~(0xF << 8);  // Clear PA2
    GPIOA->CFGLR |= (GPIO_Speed_50MHz | GPIO_AF_PP) << 8;
    
    GPIOA->CFGLR &= ~(0xF << 12); // Clear PA3
    GPIOA->CFGLR |= GPIO_IPU << 12;
    
    // USART1 @ 115200
    RCC->APB2PCENR |= RCC_APB2Periph_USART1 | RCC_APB2Periph_GPIOA;
    
    USART1->BRR = 26;  // 48MHz / 115200
    USART1->CTLR1 = USART_CTLR1_TE | USART_CTLR1_RE | USART_CTLR1_UE;
}

void ADC_Init(void)
{
    // PA1 = ADC1_IN1 (analog mic)
    GPIOA->CFGLR &= ~(0xF << 4);  // Clear PA1
    GPIOA->CFGLR |= GPIO_Mode_AIN << 4;
    
    RCC->APB2PCENR |= RCC_APB2Periph_ADC1 | RCC_APB2Periph_GPIOA;
    
    // ADC1 configuration
    ADC1->CTLR2 = ADC_CTLR2_ADON | ADC_CTLR2_CONT;
    ADC1->RSQR3 = ADC_Channel_1;
    
    // Enable ADC interrupt
    ADC1->CTLR1 |= ADC_CTLR1_EOCIE;
    NVIC_EnableIRQ(ADC1_COMP_IRQn);
}

void Timer_Init(void)
{
    // Timer2 for ADC trigger @ 8kHz
    RCC->APB1PCENR |= RCC_APB1Periph_TIM2;
    
    Timer2->PSC = 48 - 1;  // 48MHz / 48 = 1MHz
    Timer2->ATRLR = 125 - 1;  // 1MHz / 125 = 8kHz
    Timer2->SWEVGR = 1;
    Timer2->CTLR1 = 1;
    
    // TRGO to ADC
    Timer2->CTLR2 = TIM_TRGOSource_Update;
    ADC1->CTLR2 |= ADC_CTLR2_EXTSEL | ADC_CTLR2_EXTTRIG;
}

void Servo_Init(void)
{
    // PD4 = Timer2 CH1 (PWM for servo)
    GPIOD->CFGLR &= ~(0xF << 16);
    GPIOD->CFGLR |= (GPIO_Speed_50MHz | GPIO_AF_PP) << 16;
    
    // Timer2 CH1 PWM @ 50Hz
    Timer2->CH1CVR = 3000;  // 0 degrees (locked)
    Timer2->CHCTLR1 |= TIM_OCMode_PWM1 | TIM_OutputEnable;
}

// ============= Printf Support =============
int _write(int fd, char *ptr, int len)
{
    for(int i = 0; i < len; i++)
    {
        while(!(USART1->STATR & USART_STATR_TC));
        USART1->DATAR = *ptr++;
    }
    return len;
}
